spring:
  application:
    name: movieon

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

movieon:
  security:
    secret: "${JWT_SECRET}"

logging:
    level:
      org.springframework.security.web.FilterChainProxy: DEBUG
      org.springframework.security: DEBUG